version: '3'

services: 
    todosDb:
        image: mariadb
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: users
        ports:
            - "3306:3306"
        volumes:
            - ./database:/docker-entrypoint-initdb.d:ro
    
    exo_python:
        build:
            context: .
            dockerfile: Dockerfile
        environment: 
            FLASK_ENV: development
            FLASK_APP: app.py
        ports:
            - '5000:5000'