version:  '3'

services: 
    todosDb:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root  
            MYSQL_DATABASE: todos       # schemas de la bdd
        ports:
            - "3306:3306"                # 
    

            